version: '3.1'
services:
    zookeeper:
        image: zookeeper:3.4          
        ports:
          - 2181:2181
    kafka:
        image: wurstmeister/kafka:0.10.1.0
        environment:
            KAFKA_ADVERTISED_HOST_NAME: kafka
            KAFKA_ADVERTISED_PORT: 9092
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_CREATE_TOPICS: "topic-mitosis:1:1"
        ports:
            - 9092:9092
